language: php

php:
  - 7.4
  - 8.0snapshot

before_script:
  - composer install

script: php vendor/bin/phpunit --coverage-text

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email:
    - info@chrisdoehring.de
